managed_services:
  dns: true            # Setup local dnsmasq (Answers for the cluster domain)
  dhcp: true           # Setup local dhcp (Assigns IPs to LPARs)
  pxe: true            # Setup local TFTP (Boot files for Netboot)
  load_balancer: true  # Setup local HAProxy (Routes traffic for loadbalancer_ip)
  nfs: true            # Setup local NFS server for ISO hosting

controller:
  network_interface: "eth0"     # Physical interface to bind VIP and services

hmc:
  ip: "192.0.2.10"
  username: "YOUR_HMC_USERNAME"
  password: "YOUR_HMC_PASSWORD"

network:
  loadbalancer_ip: "192.0.2.100"  
  machine_network_cidr: "192.0.2.0/20" 
  gateway: "192.0.2.1"
  nameserver: ""
  dns_forwarders:
    - "198.51.100.1"
    - "198.51.100.2"
openshift:
  cluster_name: "ocp-multi"
  version: "4.21"
  base_domain: "example.local"
  
  cluster_network_cidr: "10.128.0.0/14"
  cluster_network_host_prefix: 23
  service_network: "172.30.0.0/16"
  
  pull_secret_file: "./pull-secret.json"
  ssh_public_key_file: "~/.ssh/id_rsa.pub"
  
  ocp_client_config:
    ocp_client: "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/candidate-4.21/ppc64le/openshift-client-linux.tar.gz"
    ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/candidate-4.21/ppc64le/openshift-install-linux.tar.gz"

nodes:
  boot_method: "iso"        # boot_method can be either netboot or iso
  sno:
    - name: "sno-0"
      ip: "192.0.2.101"
      existing_lpar_name: "ocp-sno-lpar-1"
      system_name: "YOUR_SYSTEM_NAME"