package services

import (
	"bytes"
	"fmt"
	"net"
	"strings"
	"text/template"

	"github.com/IBM/shiftlaunch/types"
)

// DHCPConfigData holds all variables needed to render the dhcpd.conf template
type DHCPConfigData struct {
	ClusterName string
	NetworkAddr string
	Netmask     string
	Gateway     string
	Nameserver  string
	Domain      string
	HelperIP    string
	ManagePXE   bool
	Nodes       []NodeData
}

// NodeData holds the specific node information for the template
type NodeData struct {
	Hostname   string
	MACAddress string
	IP         string
}

// dhcpdTemplate is the Go text/template for ISC DHCP (STRICTLY UNCHANGED)
const dhcpdTemplate = `# ============================================
# ISC DHCP Configuration for Cluster: {{.ClusterName}}
# Generated by ShiftLaunch
# ============================================

authoritative;
log-facility local7;

subnet {{.NetworkAddr}} netmask {{.Netmask}} {
    option routers {{.Gateway}};
    option domain-name-servers {{.Nameserver}};
    option domain-name "{{.Domain}}";
    
    default-lease-time 43200;
    max-lease-time 86400;

    # REQUIRED for IBM Power Systems legacy network boot
    allow bootp;
    {{if .ManagePXE}}
    # PXE Boot Options (Managed by ShiftLaunch)
    filename "{{.ClusterName}}/core.elf";
    next-server {{.HelperIP}};
    {{else}}
    # PXE Boot Options (Configure on your external PXE server)
    # filename "{{.ClusterName}}/core.elf";
    # next-server <your-pxe-server-ip>;
    {{end}}
{{range .Nodes}}
    host {{.Hostname}} {
        hardware ethernet {{.MACAddress}};
        fixed-address {{.IP}};
        option host-name "{{.Hostname}}";
    }
{{end}}
}
`

// GenerateISCDHCPConfig generates ISC DHCP configuration from template
func GenerateISCDHCPConfig(data DHCPConfigData) (string, error) {
	tmpl, err := template.New("dhcpd").Parse(dhcpdTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse dhcpd template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute dhcpd template: %w", err)
	}

	return buf.String(), nil
}

// PrepareISCDHCPData prepares data for ISC DHCP template from the flat AgentConfig
func PrepareISCDHCPData(cfg *types.AgentConfig) DHCPConfigData {
	network := cfg.Network

	// 1. Extract network address and calculate netmask from CIDR (e.g., "192.0.2.0/20")
	// The template requires a dotted-decimal netmask (e.g., 255.255.240.0)
	networkAddr, netmask := cidrToAddrAndMask(network.MachineCIDR)

	// 2. Prepare node data using the unified nodes hierarchy
	// GetAllNodes handles SNO, Masters, and Workers pointers [cite: 113, 121]
	allNodes := cfg.GetAllNodes()
	nodeData := make([]NodeData, 0, len(allNodes))
	for _, node := range allNodes {
		mac := strings.ToLower(node.MACAddress)
		// Let empty MAC pass through to template for proper conditional rendering

		nodeData = append(nodeData, NodeData{
			Hostname:   node.Hostname,
			MACAddress: mac,
			IP:         node.IP,
		})
	}

	// 3. Map new configuration fields to template variables
	return DHCPConfigData{
		ClusterName: cfg.OpenShift.ClusterName, // [cite: 109]
		NetworkAddr: networkAddr,               // [cite: 117]
		Netmask:     netmask,                   // Calculated from CIDR
		Gateway:     network.Gateway,           // [cite: 117]
		Nameserver:  cfg.Services.DNS.GetExternal(),
		Domain:      cfg.OpenShift.BaseDomain,     // [cite: 109]
		HelperIP:    cfg.Network.ControllerIP,     // Controller IP replaces Helper
		ManagePXE:   cfg.Services.PXE.IsManaged(), // Toggle based on Services
		Nodes:       nodeData,
	}
}

// cidrToAddrAndMask converts "192.0.2.0/20" to "192.0.2.0" and "255.255.240.0"
func cidrToAddrAndMask(cidr string) (string, string) {
	ip, ipnet, err := net.ParseCIDR(cidr)
	if err != nil {
		return cidr, "255.255.255.0" // Safe fallback
	}

	// Calculate dotted-decimal netmask from prefix length
	mask := net.IP(ipnet.Mask)
	return ip.String(), mask.String()
}
