package services

import (
	"bytes"
	"context"
	"fmt"
	"text/template"

	"github.ibm.com/sudeeshjohn/shiftlaunch/localexec"
	"github.ibm.com/sudeeshjohn/shiftlaunch/types"
)

const helperScriptTemplate = `#!/bin/bash
# OpenShift Installation Helper Script
# Cluster: {{.ClusterName}}
# Generated by ocp-upi-deployer

set -e

CLUSTER_NAME="{{.ClusterName}}"
BASE_DOMAIN="{{.BaseDomain}}"
HTTP_DIR="{{.HTTPDir}}"
API_VIP="{{.VIP}}"
HELPER_IP="{{.HelperIP}}"

echo "OpenShift Installation Helper for ${CLUSTER_NAME}.${BASE_DOMAIN}"
echo "================================================================"
echo ""

# Function to check ignition files
check_ignition() {
    echo "Checking ignition files..."
    local found=0
    for file in bootstrap.ign master.ign worker.ign; do
        if [ -f "${HTTP_DIR}/ignition/${file}" ]; then
            local size=$(du -h "${HTTP_DIR}/ignition/${file}" | awk '{print $1}')
            echo "  ${file} (${size})"
            found=$((found + 1))
        else
            echo "  ✗ ${file} missing"
        fi
    done
    echo "  Found ${found} ignition file(s)"
}

# Function to check RHCOS images
check_rhcos() {
    echo "Checking RHCOS images..."
    local found=0
    for file in rhcos-live-kernel-ppc64le rhcos-live-initramfs.ppc64le.img rhcos-live-rootfs.ppc64le.img; do
        if [ -f "${HTTP_DIR}/rhcos/${file}" ]; then
            local size=$(du -h "${HTTP_DIR}/rhcos/${file}" | awk '{print $1}')
            echo "  ${file} (${size})"
            found=$((found + 1))
        else
            echo "  ✗ ${file} missing"
        fi
    done
    echo "  Found ${found}/3 RHCOS images"
}

# Function to check OpenShift tools
check_tools() {
    echo "Checking OpenShift tools..."
    local found=0
    for tool in openshift-install oc kubectl; do
        if [ -f "${HTTP_DIR}/tools/${tool}" ]; then
            if [ -x "${HTTP_DIR}/tools/${tool}" ]; then
                echo "  ${tool} (executable)"
            else
                echo "  ⚠ ${tool} (not executable)"
            fi
            found=$((found + 1))
        else
            echo "  ✗ ${tool} missing"
        fi
    done
    echo "  Found ${found}/3 tools"
}

# Function to test HTTP access
test_http() {
    echo "Testing HTTP access..."
    local base_url="http://${HELPER_IP}:8080/${CLUSTER_NAME}"
    
    local tests=(
        "ignition/bootstrap.ign:Bootstrap ignition"
        "rhcos/rhcos-live-kernel-ppc64le:RHCOS kernel"
        "rhcos/rhcos-live-initramfs.ppc64le.img:RHCOS initramfs"
        "rhcos/rhcos-live-rootfs.ppc64le.img:RHCOS rootfs"
    )
    
    local passed=0
    for test in "${tests[@]}"; do
        local path="${test%%:*}"
        local desc="${test##*:}"
        local url="${base_url}/${path}"
        
        if curl -s -f -I "${url}" > /dev/null 2>&1; then
            echo "  ${desc} accessible"
            passed=$((passed + 1))
        else
            echo "  ✗ ${desc} not accessible"
            echo "    URL: ${url}"
        fi
    done
    echo "  Passed ${passed}/${#tests[@]} HTTP tests"
}

# Function to show disk usage
show_disk_usage() {
    echo "Disk usage:"
    du -sh "${HTTP_DIR}"/* 2>/dev/null | while read size path; do
        echo "  ${size}  $(basename ${path})"
    done
    echo ""
    echo "Total: $(du -sh ${HTTP_DIR} | awk '{print $1}')"
}

# Function to list files
list_files() {
    echo "Files in ${HTTP_DIR}:"
    find "${HTTP_DIR}" -type f | while read file; do
        local size=$(du -h "${file}" | awk '{print $1}')
        local rel_path="${file#${HTTP_DIR}/}"
        echo "  ${rel_path} (${size})"
    done
}

# Function to show URLs
show_urls() {
    echo "HTTP URLs for cluster ${CLUSTER_NAME}:"
    echo ""
    echo "Ignition files:"
    echo "  Bootstrap: http://${HELPER_IP}:8080/${CLUSTER_NAME}/ignition/bootstrap.ign"
    echo "  Master:    http://${HELPER_IP}:8080/${CLUSTER_NAME}/ignition/master.ign"
    echo "  Worker:    http://${HELPER_IP}:8080/${CLUSTER_NAME}/ignition/worker.ign"
    echo ""
    echo "RHCOS images:"
    echo "  Kernel:    http://${HELPER_IP}:8080/${CLUSTER_NAME}/rhcos/rhcos-live-kernel-ppc64le"
    echo "  Initramfs: http://${HELPER_IP}:8080/${CLUSTER_NAME}/rhcos/rhcos-live-initramfs.ppc64le.img"
    echo "  Rootfs:    http://${HELPER_IP}:8080/${CLUSTER_NAME}/rhcos/rhcos-live-rootfs.ppc64le.img"
}

# Main menu
case "${1:-check}" in
    check)
        check_ignition
        echo ""
        check_rhcos
        echo ""
        check_tools
        echo ""
        test_http
        ;;
    ignition)
        check_ignition
        ;;
    rhcos)
        check_rhcos
        ;;
    tools)
        check_tools
        ;;
    http)
        test_http
        ;;
    disk)
        show_disk_usage
        ;;
    list)
        list_files
        ;;
    urls)
        show_urls
        ;;
    *)
        echo "Usage: $0 {check|ignition|rhcos|tools|http|disk|list|urls}"
        echo ""
        echo "Commands:"
        echo "  check     - Run all checks (default)"
        echo "  ignition  - Check ignition files"
        echo "  rhcos     - Check RHCOS images"
        echo "  tools     - Check OpenShift tools"
        echo "  http      - Test HTTP accessibility"
        echo "  disk      - Show disk usage"
        echo "  list      - List all files"
        echo "  urls      - Show HTTP URLs"
        exit 1
        ;;
esac
`

// GenerateHelperScript generates the install helper script for a cluster
func GenerateHelperScript(cfg *types.AgentConfig, port int) string {
	tmpl, err := template.New("helper").Parse(helperScriptTemplate)
	if err != nil {
		return fmt.Sprintf("# Error generating template: %v", err)
	}

	data := struct {
		ClusterName string
		BaseDomain  string
		HTTPDir     string
		VIP         string
		HelperIP    string
		HTTPPort    int
	}{
		ClusterName: cfg.OpenShift.ClusterName,
		BaseDomain:  cfg.OpenShift.BaseDomain,
		HTTPDir:     fmt.Sprintf("/var/www/html/%s", cfg.OpenShift.ClusterName),
		VIP:         cfg.Network.LoadBalancerIP,
		HelperIP:    cfg.Controller.IP,
		HTTPPort:    port,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Sprintf("# Error executing template: %v", err)
	}

	return buf.String()
}

// ============================================================================
// HTTPD CONFIGURATION
// ============================================================================

// ConfigureHTTPD globally configures Apache to serve /var/www/html idempotently
func ConfigureHTTPD(ctx context.Context,exec *localexec.LocalClient, port int) error {
	// 1. Check if httpd is already perfectly configured
	checkCmd := fmt.Sprintf(`grep -q "^Listen %d" /etc/httpd/conf/httpd.conf && grep -q '^DocumentRoot "/var/www/html"' /etc/httpd/conf/httpd.conf`, port)

	if _, err := exec.Execute(ctx,checkCmd); err == nil {
		exec.SystemctlEnable(ctx,"httpd")
		exec.Execute(ctx,"sudo systemctl start httpd")
		return nil
	}

	// CRITICAL: Shield from cancellation! Killing sed -i mid-execution will
	// permanently destroy the global Apache configuration file!
	shieldedCtx := context.WithoutCancel(ctx)

	// 2. If we reach here, httpd needs to be configured
	if _, err := exec.Execute(shieldedCtx, fmt.Sprintf("sudo sed -i 's/^Listen .*/Listen %d/g' /etc/httpd/conf/httpd.conf", port)); err != nil {
		return fmt.Errorf("failed to update Listen port in httpd.conf: %w", err)
	}

	// Ensure DocumentRoot is set strictly to /var/www/html
	if _, err := exec.Execute(shieldedCtx, `sudo sed -i 's|^DocumentRoot .*|DocumentRoot "/var/www/html"|g' /etc/httpd/conf/httpd.conf`); err != nil {
		return fmt.Errorf("failed to update DocumentRoot in httpd.conf: %w", err)
	}

	// Ensure SELinux allows Apache to read the standard directory
	exec.Execute(shieldedCtx, "sudo chcon -Rt httpd_sys_content_t /var/www/html")

	// 3. Enable and restart the service
	if err := exec.SystemctlEnable(shieldedCtx, "httpd"); err != nil {
		return fmt.Errorf("failed to enable httpd service: %w", err)
	}
	if err := exec.SystemctlRestart(shieldedCtx, "httpd"); err != nil {
		return fmt.Errorf("failed to restart httpd service: %w", err)
	}

	return nil
}